#***Spam email detection***

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df=pd.read_csv('email.csv')

In [5]:
df

            Category                                            Message
0                ham  Go until jurong point, crazy.. Available only ...
1                ham                      Ok lar... Joking wif u oni...
2               spam  Free entry in 2 a wkly comp to win FA Cup fina...
3                ham  U dun say so early hor... U c already then say...
4                ham  Nah I don't think he goes to usf, he lives aro...
...              ...                                                ...
5568             ham               Will ü b going to esplanade fr home?
5569             ham  Pity, * was in mood for that. So...any other s...
5570             ham  The guy did some bitching but I acted like i'd...
5571             ham                         Rofl. Its true to its name
5572  {"mode":"full"                                    isActive:false}

[5573 rows x 2 columns]

In [6]:
df.loc[:,'class']=df.loc[:,'Category'].map({'ham':1,'spam':0})

In [7]:
df.drop(columns=['Category'],axis=1,inplace=True)

In [8]:
df.loc[:,'class'].unique()

array([ 1.,  0., nan])

In [9]:
df.dropna(subset=['class'], inplace=True)

In [10]:
df.isnull().sum()

Message    0
class      0
dtype: int64

In [11]:
df

                                                Message  class
0     Go until jurong point, crazy.. Available only ...    1.0
1                         Ok lar... Joking wif u oni...    1.0
2     Free entry in 2 a wkly comp to win FA Cup fina...    0.0
3     U dun say so early hor... U c already then say...    1.0
4     Nah I don't think he goes to usf, he lives aro...    1.0
...                                                 ...    ...
5567  This is the 2nd time we have tried 2 contact u...    0.0
5568               Will ü b going to esplanade fr home?    1.0
5569  Pity, * was in mood for that. So...any other s...    1.0
5570  The guy did some bitching but I acted like i'd...    1.0
5571                         Rofl. Its true to its name    1.0

[5572 rows x 2 columns]

In [12]:
df.loc[5:'message']

                                                Message  class
5     FreeMsg Hey there darling it's been 3 week's n...    0.0
6     Even my brother is not like to speak with me. ...    1.0
7     As per your request 'Melle Melle (Oru Minnamin...    1.0
8     WINNER!! As a valued network customer you have...    0.0
9     Had your mobile 11 months or more? U R entitle...    0.0
...                                                 ...    ...
5567  This is the 2nd time we have tried 2 contact u...    0.0
5568               Will ü b going to esplanade fr home?    1.0
5569  Pity, * was in mood for that. So...any other s...    1.0
5570  The guy did some bitching but I acted like i'd...    1.0
5571                         Rofl. Its true to its name    1.0

[5567 rows x 2 columns]

In [13]:
import re
import string

In [14]:
def clean_text (text):
  text= text.lower()
  # remove html tags
  text = re.sub(r'<.*?>',"",text)
  # remove urls
  text = re.sub(r'http\S+|www\S+','',text)
  # remove emojis
  text = re.sub(r'[^x00-\x7F]+',' ',text)
  # special characters
  text = re.sub(r'[^a-z0-9\s]','',text)
  # white space
  text = re.sub(r'\s+',' ',text).strip()

  return text

In [15]:
df.loc[:,'cleaned_text']=df.loc[:,'Message'].apply(clean_text)

In [16]:
df

,Message,class,cleaned_text
0,"Go until jurong point, crazy.. Available only ...",1.0,go until jurong point crazy available only in ...
1,Ok lar... Joking wif u oni...,1.0,ok lar joking wif u oni
2,Free entry in 2 a wkly comp to win FA Cup fina...,0.0,free entry in 2 a wkly comp to win fa cup fina...
3,U dun say so early hor... U c already then say...,1.0,u dun say so early hor u c already then say
4,"Nah I don't think he goes to usf, he lives aro...",1.0,nah i don t think he goes to usf he lives arou...
...,...,...,...
5567,This is the 2nd time we have tried 2 contact u...,0.0,this is the 2nd time we have tried 2 contact u...
5568,Will ü b going to esplanade fr home?,1.0,will b going to esplanade fr home
5569,"Pity, * was in mood for that. So...any other s...",1.0,pity was in mood for that so any other suggest...
5570,The guy did some bitching but I acted like i'd...,1.0,the guy did some bitching but i acted like i d...
5571,Rofl. Its true to its name,1.0,rofl its true to its name

In [17]:
x=df['cleaned_text']
y=df['class']

In [26]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

#count vectorizer

In [28]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
x_new_train=cv.fit_transform(x_train)
x_new_test=cv.transform(x_test)

In [29]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(x_new_train,y_train)
y_pred=model.predict(x_new_test)

In [31]:
from sklearn.metrics import accuracy_score,confusion_matrix,recall_score,precision_score,f1_score
accuracy_score(y_test,y_pred)

0.9901345291479821

In [32]:
confusion_matrix(y_test,y_pred)

array([[138,  11],
       [  0, 966]])

In [33]:
recall_score(y_test,y_pred)

1.0

In [34]:
precision_score(y_test,y_pred)

0.9887410440122825

In [35]:
f1_score(y_test,y_pred)

0.9943386515697376

#predictions

In [40]:
msg=input("enter the message")
test=cv.transform([msg])
pred=model.predict(test)
if pred[0]==0:
 print('spam')
else:
  print("ham")

enter the messageI love you
ham

#TF_IDF

In [44]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf=TfidfVectorizer()
x_new_train=tf.fit_transform(x_train)
x_new_test=tf.transform(x_test)

In [48]:
model=MultinomialNB()
model.fit(x_new_train,y_train)
y_pred=model.predict(x_new_test)

In [50]:
accuracy_score(y_test,y_pred)

0.9587443946188341

In [51]:
confusion_matrix(y_test,y_pred)

array([[103,  46],
       [  0, 966]])

In [52]:
recall_score(y_test,y_pred)

1.0

In [53]:
precision_score(y_test,y_pred)

0.9545454545454546

In [54]:
f1_score(y_test,y_pred)

0.9767441860465116

In [59]:
msg=input("enter the message")
test=cv.transform([msg])
pred=model.predict(test)
if pred[0]==0:
 print('spam')
else:
  print("ham")

enter the messageI love you
ham

In [60]:
msg=input("enter the message")
test=cv.transform([msg])
pred=model.predict(test)
if pred[0]==0:
 print('spam')
else:
  print("ham")

enter the messageHey you have won 10000m$ worth prize , congratulations
spam